version: 0.2
 
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - apt update 
      - apt install -y unzip
      - apt install openjdk-17-jdk -y

  build:
    commands:
      - echo Build started on `date`
      - zip hello.zip ./index.html 
   
artifacts:
  files:
    - index.html
    - appspec.yml
    - scripts/install_dependencies
    - scripts/start_server
